// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	urlMapFieldNames          = builder.RawFieldNames(&UrlMap{})
	urlMapRows                = strings.Join(urlMapFieldNames, ",")
	urlMapRowsExpectAutoSet   = strings.Join(stringx.Remove(urlMapFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	urlMapRowsWithPlaceHolder = strings.Join(stringx.Remove(urlMapFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	urlMapModel interface {
		Insert(ctx context.Context, data *UrlMap) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UrlMap, error)
		FindOneByLongUrlMd5(ctx context.Context, longUrlMd5 string) (*UrlMap, error)
		FindOneByShortUrl(ctx context.Context, shortUrl string) (*UrlMap, error)
		Update(ctx context.Context, data *UrlMap) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUrlMapModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UrlMap struct {
		Id         uint64    `db:"id"`
		CreatedAt  time.Time `db:"created_at"`
		UpdatedAt  time.Time `db:"updated_at"`
		LongUrl    string    `db:"long_url"`
		LongUrlMd5 string    `db:"long_url_md5"`
		ShortUrl   string    `db:"short_url"`
	}
)

func newUrlMapModel(conn sqlx.SqlConn) *defaultUrlMapModel {
	return &defaultUrlMapModel{
		conn:  conn,
		table: "`url_map`",
	}
}

func (m *defaultUrlMapModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUrlMapModel) FindOne(ctx context.Context, id uint64) (*UrlMap, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", urlMapRows, m.table)
	var resp UrlMap
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUrlMapModel) FindOneByLongUrlMd5(ctx context.Context, longUrlMd5 string) (*UrlMap, error) {
	var resp UrlMap
	query := fmt.Sprintf("select %s from %s where `long_url_md5` = ? limit 1", urlMapRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, longUrlMd5)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUrlMapModel) FindOneByShortUrl(ctx context.Context, shortUrl string) (*UrlMap, error) {
	var resp UrlMap
	query := fmt.Sprintf("select %s from %s where `short_url` = ? limit 1", urlMapRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, shortUrl)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUrlMapModel) Insert(ctx context.Context, data *UrlMap) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, urlMapRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.LongUrl, data.LongUrlMd5, data.ShortUrl)
	return ret, err
}

func (m *defaultUrlMapModel) Update(ctx context.Context, newData *UrlMap) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, urlMapRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.LongUrl, newData.LongUrlMd5, newData.ShortUrl, newData.Id)
	return err
}

func (m *defaultUrlMapModel) tableName() string {
	return m.table
}
