// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type ConvertReq struct {
	LongUrl string `json:"long_url" validate:"required"`
}

type ConvertResp struct {
	ShortUrl string `json:"short_url"`
}

type ShowReq struct {
	ShortUrl string `path:"short_url" validate:"required"`
}

type ShowResp struct {
	LongUrl string `json:"long_url"`
}
